apiVersion: apps/v1
kind: Deployment
metadata:
  name: bilibilipro
spec:
  selector:
    matchLabels:
      app: bilibilipro
  template:
    metadata:
      labels:
        app: bilibilipro
    spec:
      containers:
        - name: bilibilipro
          image: ghcr.io/zzzhe2333/bili_tool_web:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 80m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 120Mi
