# Tencent SCF sample for ZzzHe2333/BiliBiliToolPro
component: scf
name: bilibili_tool

inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou
  description: BiliBiliToolPro scheduled tasks
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events:
    - timer:
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer:
        parameters:
          name: VipBigPointTask
          cronExpression: "0 07 01 * * * *"
          enable: true
          argument: VipBigPoint
  environment:
    variables:
      Zzz_BiliBiliCookies__1: "" # cookie，必填；建议通过云端安全配置注入真实值
